name: openfgl
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accessible-pygments==0.0.5
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - dgl==2.1.0
      - docutils==0.21.2
      - dtaidistance==2.3.13
      - exceptiongroup==1.3.0
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - furo==2025.9.25
      - h11==0.16.0
      - idna==3.4
      - imagesize==1.4.1
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - latexcodec==3.0.1
      - llvmlite==0.45.1
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - munkres==1.1.4
      - networkx==3.3
      - numba==0.62.1
      - numpy==1.26.4
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - propcache==0.4.1
      - psutil==7.1.3
      - pybtex==0.25.1
      - pybtex-docutils==1.0.3
      - pygments==2.19.2
      - pymetis==2025.2.2
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.14
      - scikit-learn==1.7.2
      - scikit-network==0.33.3
      - scipy==1.15.3
      - six==1.17.0
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - soupsieve==2.8
      - sphinx==8.1.3
      - sphinx-autobuild==2024.10.3
      - sphinx-basic-ng==1.0.0b2
      - sphinx-gallery==0.19.0
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-bibtex==2.6.5
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - starlette==0.50.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tomli==2.3.0
      - torch==2.1.0+cpu
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torchdata==0.11.0
      - torchvision==0.16.0+cpu
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==1.26.13
      - uvicorn==0.38.0
      - watchfiles==1.1.1
      - websockets==15.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /arf/home/esunar/miniconda3/envs/openfgl
